import { Roboto, Shrikhand } from "next/font/google";
import "./globals.css";
import "./styles.css";
import Link from "next/link";
import styles from "./layout.module.css";
import Header from "@/components/Header/Header";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faUtensils, faHandshakeAngle } from "@fortawesome/free-solid-svg-icons";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
});

const shrikhand = Shrikhand({
  weight: '400',
  variable: '--font-shrikhand',
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`${roboto.variable} ${shrikhand.variable}`}>
        <div className={styles.page}>
          <Header />

          <main className={styles.mainContent}>
            <div className={styles.contentWrapper}>
              {children}
            </div>
          </main>

          <footer className={styles.footer}>
            <nav>
              <a href="#" className={styles.footerLink}>
                <FontAwesomeIcon icon={faUtensils} className={styles.footerIcon} />
                Proposer un restaurant
              </a>
              <a href="#" className={styles.footerLink}>
                <FontAwesomeIcon icon={faHandshakeAngle} className={styles.footerIcon} />
                Devenir partenaire
              </a>
              <a href="#">Mentions légales</a>
              <a href="#">Contact</a>
            </nav>
            <Link href="/" className={styles.footerLogo}>
              ohmyfood
            </Link>
          </footer>
        </div>
      </body>
    </html>
  );
}
